/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_DIGITAL_EN 0x0100u    /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u           /*!<@brief Selects pin function 0 */
#define IOCON_PIO_FUNC1 0x01u           /*!<@brief Selects pin function 1 */
#define IOCON_PIO_FUNC6 0x06u           /*!<@brief Selects pin function 6 */
#define IOCON_PIO_I2CDRIVE_HIGH 0x0400u /*!<@brief High drive: 20 mA */
#define IOCON_PIO_I2CFILTER_EN 0x00u    /*!<@brief I2C 50 ns glitch filter enabled */
#define IOCON_PIO_I2CSLEW_I2C 0x00u     /*!<@brief I2C mode */
#define IOCON_PIO_INPFILT_OFF 0x0200u   /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u          /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u      /*!<@brief No addition pin function */
#define IOCON_PIO_MODE_PULLUP 0x20u     /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u    /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_FAST 0x0400u     /*!<@brief Fast mode, slew rate control is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u   /*!<@brief Standard mode, output slew rate control is enabled */
#define PIO017_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO017_FUNC_ALT7 0x07u          /*!<@brief Selects pin function.: Alternative connection 7. */
#define PIO226_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO226_FUNC_ALT0 0x00u          /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO410_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO410_FUNC_ALT1 0x01u          /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO411_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO411_FUNC_ALT1 0x01u          /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO412_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO412_FUNC_ALT1 0x01u          /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO413_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO413_FUNC_ALT1 0x01u          /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO414_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO414_FUNC_ALT1 0x01u          /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO415_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO415_FUNC_ALT1 0x01u          /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO416_DIGIMODE_DIGITAL 0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO416_FUNC_ALT1 0x01u          /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO48_DIGIMODE_DIGITAL 0x01u    /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO48_FUNC_ALT1 0x01u           /*!<@brief Selects pin function.: Alternative connection 1. */

/*! @name FC0_TXD_SCL_MISO (coord A2), U24[12]/P0_30-ISP_FC0_TXD
  @{ */
#define BOARD_INITPINS_ISP_FC0_TXD_PERIPHERAL FLEXCOMM0              /*!<@brief Device name: FLEXCOMM0 */
#define BOARD_INITPINS_ISP_FC0_TXD_SIGNAL TXD_SCL_MISO               /*!<@brief FLEXCOMM0 signal: TXD_SCL_MISO */
#define BOARD_INITPINS_ISP_FC0_TXD_PIN_NAME FC0_TXD_SCL_MISO         /*!<@brief Pin name */
#define BOARD_INITPINS_ISP_FC0_TXD_LABEL "U24[12]/P0_30-ISP_FC0_TXD" /*!<@brief Label */
#define BOARD_INITPINS_ISP_FC0_TXD_NAME "ISP_FC0_TXD"                /*!<@brief Identifier name */
                                                                     /* @} */

/*! @name FC0_RXD_SDA_MOSI (coord B13), U24[13]/P0_29-ISP_FC0_RXD
  @{ */
#define BOARD_INITPINS_ISP_FC0_RXD_PERIPHERAL FLEXCOMM0              /*!<@brief Device name: FLEXCOMM0 */
#define BOARD_INITPINS_ISP_FC0_RXD_SIGNAL RXD_SDA_MOSI               /*!<@brief FLEXCOMM0 signal: RXD_SDA_MOSI */
#define BOARD_INITPINS_ISP_FC0_RXD_PIN_NAME FC0_RXD_SDA_MOSI         /*!<@brief Pin name */
#define BOARD_INITPINS_ISP_FC0_RXD_LABEL "U24[13]/P0_29-ISP_FC0_RXD" /*!<@brief Label */
#define BOARD_INITPINS_ISP_FC0_RXD_NAME "ISP_FC0_RXD"                /*!<@brief Identifier name */
                                                                     /* @} */

/*! @name EMC_D(0) (coord E9), U28[A8]/RP3[4]/JS35[1]/U24[11]/J14[3]/P0_2-ISP_FC3_MISO/P0_2-EMC_D0
  @{ */
/*!
 * @brief Device name: EMC */
#define BOARD_INITPINS_EMC_D0_PERIPHERAL EMC
/*!
 * @brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D0_SIGNAL EMC_D
/*!
 * @brief EMC EMC_D channel: 0 */
#define BOARD_INITPINS_EMC_D0_CHANNEL 0
/*!
 * @brief Pin name */
#define BOARD_INITPINS_EMC_D0_PIN_NAME EMC_D(0)
/*!
 * @brief Label */
#define BOARD_INITPINS_EMC_D0_LABEL "U28[A8]/RP3[4]/JS35[1]/U24[11]/J14[3]/P0_2-ISP_FC3_MISO/P0_2-EMC_D0"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_EMC_D0_NAME "EMC_D0"
/* @} */

/*! @name EMC_D(1) (coord A10), U28[B9]/RP3[3]/JS34[1]/U26[11]/J14[2]/P0_3-ISP_FC3_MOSI/P0_3-EMC_D1
  @{ */
/*!
 * @brief Device name: EMC */
#define BOARD_INITPINS_EMC_D1_PERIPHERAL EMC
/*!
 * @brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D1_SIGNAL EMC_D
/*!
 * @brief EMC EMC_D channel: 1 */
#define BOARD_INITPINS_EMC_D1_CHANNEL 1
/*!
 * @brief Pin name */
#define BOARD_INITPINS_EMC_D1_PIN_NAME EMC_D(1)
/*!
 * @brief Label */
#define BOARD_INITPINS_EMC_D1_LABEL "U28[B9]/RP3[3]/JS34[1]/U26[11]/J14[2]/P0_3-ISP_FC3_MOSI/P0_3-EMC_D1"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_EMC_D1_NAME "EMC_D1"
/* @} */

/*! @name EMC_D(2) (coord C8), U28[B8]/RP3[2]/JS32[3]/SW4/P0_4-ISP0/P0_4-EMC_D2
  @{ */
/*!
 * @brief Device name: EMC */
#define BOARD_INITPINS_EMC_D2_PERIPHERAL EMC
/*!
 * @brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D2_SIGNAL EMC_D
/*!
 * @brief EMC EMC_D channel: 2 */
#define BOARD_INITPINS_EMC_D2_CHANNEL 2
/*!
 * @brief Pin name */
#define BOARD_INITPINS_EMC_D2_PIN_NAME EMC_D(2)
/*!
 * @brief Label */
#define BOARD_INITPINS_EMC_D2_LABEL "U28[B8]/RP3[2]/JS32[3]/SW4/P0_4-ISP0/P0_4-EMC_D2"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_EMC_D2_NAME "EMC_D2"
/* @} */

/*! @name EMC_D(3) (coord E7), U28[C9]/RP3[1]/JS32[1]/SW3/P0_5-ISP1/P0_5-EMC_D3
  @{ */
/*!
 * @brief Device name: EMC */
#define BOARD_INITPINS_EMC_D3_PERIPHERAL EMC
/*!
 * @brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D3_SIGNAL EMC_D
/*!
 * @brief EMC EMC_D channel: 3 */
#define BOARD_INITPINS_EMC_D3_CHANNEL 3
/*!
 * @brief Pin name */
#define BOARD_INITPINS_EMC_D3_PIN_NAME EMC_D(3)
/*!
 * @brief Label */
#define BOARD_INITPINS_EMC_D3_LABEL "U28[C9]/RP3[1]/JS32[1]/SW3/P0_5-ISP1/P0_5-EMC_D3"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_EMC_D3_NAME "EMC_D3"
/* @} */

/*! @name EMC_D(4) (coord A5), U28[C8]/RP5[4]/SW2/P0_6-ISP2/P0_6-EMC_D4
  @{ */
/*!
 * @brief Device name: EMC */
#define BOARD_INITPINS_EMC_D4_PERIPHERAL EMC
/*!
 * @brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D4_SIGNAL EMC_D
/*!
 * @brief EMC EMC_D channel: 4 */
#define BOARD_INITPINS_EMC_D4_CHANNEL 4
/*!
 * @brief Pin name */
#define BOARD_INITPINS_EMC_D4_PIN_NAME EMC_D(4)
/*!
 * @brief Label */
#define BOARD_INITPINS_EMC_D4_LABEL "U28[C8]/RP5[4]/SW2/P0_6-ISP2/P0_6-EMC_D4"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_EMC_D4_NAME "EMC_D4"
/* @} */

/*! @name EMC_D(5) (coord H12), U28[D9]/RP5[3]/P0_7-EMC_D5
  @{ */
#define BOARD_INITPINS_EMC_D5_PERIPHERAL EMC                     /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D5_SIGNAL EMC_D                       /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D5_CHANNEL 5                          /*!<@brief EMC EMC_D channel: 5 */
#define BOARD_INITPINS_EMC_D5_PIN_NAME EMC_D(5)                  /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D5_LABEL "U28[D9]/RP5[3]/P0_7-EMC_D5" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D5_NAME "EMC_D5"                      /*!<@brief Identifier name */
                                                                 /* @} */

/*! @name EMC_D(6) (coord H10), U28[D8]/RP5[2]/P0_8-EMC_D6
  @{ */
#define BOARD_INITPINS_EMC_D6_PERIPHERAL EMC                     /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D6_SIGNAL EMC_D                       /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D6_CHANNEL 6                          /*!<@brief EMC EMC_D channel: 6 */
#define BOARD_INITPINS_EMC_D6_PIN_NAME EMC_D(6)                  /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D6_LABEL "U28[D8]/RP5[2]/P0_8-EMC_D6" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D6_NAME "EMC_D6"                      /*!<@brief Identifier name */
                                                                 /* @} */

/*! @name EMC_D(7) (coord G12), U28[E9]/RP5[1]/P0_9-EMC_D7
  @{ */
#define BOARD_INITPINS_EMC_D7_PERIPHERAL EMC                     /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D7_SIGNAL EMC_D                       /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D7_CHANNEL 7                          /*!<@brief EMC EMC_D channel: 7 */
#define BOARD_INITPINS_EMC_D7_PIN_NAME EMC_D(7)                  /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D7_LABEL "U28[E9]/RP5[1]/P0_9-EMC_D7" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D7_NAME "EMC_D7"                      /*!<@brief Identifier name */
                                                                 /* @} */

/*! @name EMC_WEN (coord L4), U28[F9]/P0_15-EMC_WEn
  @{ */
#define BOARD_INITPINS_EMC_WEn_PERIPHERAL EMC                /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_WEn_SIGNAL EMC_WE                 /*!<@brief EMC signal: EMC_WE */
#define BOARD_INITPINS_EMC_WEn_PIN_NAME EMC_WEN              /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_WEn_LABEL "U28[F9]/P0_15-EMC_WEn" /*!<@brief Label */
#define BOARD_INITPINS_EMC_WEn_NAME "EMC_WEn"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name EMC_A(0) (coord C14), U28[H7]/P0_18-EMC_A0
  @{ */
#define BOARD_INITPINS_EMC_A0_PERIPHERAL EMC               /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A0_SIGNAL EMC_A                 /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A0_CHANNEL 0                    /*!<@brief EMC EMC_A channel: 0 */
#define BOARD_INITPINS_EMC_A0_PIN_NAME EMC_A(0)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A0_LABEL "U28[H7]/P0_18-EMC_A0" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A0_NAME "EMC_A0"                /*!<@brief Identifier name */
                                                           /* @} */

/*! @name EMC_A(1) (coord C6), U28[H8]/P0_19-EMC_A1
  @{ */
#define BOARD_INITPINS_EMC_A1_PERIPHERAL EMC               /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A1_SIGNAL EMC_A                 /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A1_CHANNEL 1                    /*!<@brief EMC EMC_A channel: 1 */
#define BOARD_INITPINS_EMC_A1_PIN_NAME EMC_A(1)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A1_LABEL "U28[H8]/P0_19-EMC_A1" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A1_NAME "EMC_A1"                /*!<@brief Identifier name */
                                                           /* @} */

/*! @name EMC_A(2) (coord D13), U28[J8]/P0_20-EMC_A2
  @{ */
#define BOARD_INITPINS_EMC_A2_PERIPHERAL EMC               /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A2_SIGNAL EMC_A                 /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A2_CHANNEL 2                    /*!<@brief EMC EMC_A channel: 2 */
#define BOARD_INITPINS_EMC_A2_PIN_NAME EMC_A(2)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A2_LABEL "U28[J8]/P0_20-EMC_A2" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A2_NAME "EMC_A2"                /*!<@brief Identifier name */
                                                           /* @} */

/*! @name EMC_A(3) (coord C13), U28[J7]/P0_21-EMC_A3
  @{ */
#define BOARD_INITPINS_EMC_A3_PERIPHERAL EMC               /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A3_SIGNAL EMC_A                 /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A3_CHANNEL 3                    /*!<@brief EMC EMC_A channel: 3 */
#define BOARD_INITPINS_EMC_A3_PIN_NAME EMC_A(3)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A3_LABEL "U28[J7]/P0_21-EMC_A3" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A3_NAME "EMC_A3"                /*!<@brief Identifier name */
                                                           /* @} */

/*! @name EMC_D(11) (coord D4), U28[C2]/RP4[1]/P1_4-EMC_D11
  @{ */
#define BOARD_INITPINS_EMC_D11_PERIPHERAL EMC                      /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D11_SIGNAL EMC_D                        /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D11_CHANNEL 11                          /*!<@brief EMC EMC_D channel: 11 */
#define BOARD_INITPINS_EMC_D11_PIN_NAME EMC_D(11)                  /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D11_LABEL "U28[C2]/RP4[1]/P1_4-EMC_D11" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D11_NAME "EMC_D11"                      /*!<@brief Identifier name */
                                                                   /* @} */

/*! @name EMC_A(4) (coord E4), U28[J3]/P1_5-EMC_A4
  @{ */
#define BOARD_INITPINS_EMC_A4_PERIPHERAL EMC              /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A4_SIGNAL EMC_A                /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A4_CHANNEL 4                   /*!<@brief EMC EMC_A channel: 4 */
#define BOARD_INITPINS_EMC_A4_PIN_NAME EMC_A(4)           /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A4_LABEL "U28[J3]/P1_5-EMC_A4" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A4_NAME "EMC_A4"               /*!<@brief Identifier name */
                                                          /* @} */

/*! @name EMC_A(5) (coord G4), U28[J2]/P1_6-EMC_A5
  @{ */
#define BOARD_INITPINS_EMC_A5_PERIPHERAL EMC              /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A5_SIGNAL EMC_A                /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A5_CHANNEL 5                   /*!<@brief EMC EMC_A channel: 5 */
#define BOARD_INITPINS_EMC_A5_PIN_NAME EMC_A(5)           /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A5_LABEL "U28[J2]/P1_6-EMC_A5" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A5_NAME "EMC_A5"               /*!<@brief Identifier name */
                                                          /* @} */

/*! @name EMC_A(6) (coord N1), U28[H3]/P1_7-EMC_A6
  @{ */
#define BOARD_INITPINS_EMC_A6_PERIPHERAL EMC              /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A6_SIGNAL EMC_A                /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A6_CHANNEL 6                   /*!<@brief EMC EMC_A channel: 6 */
#define BOARD_INITPINS_EMC_A6_PIN_NAME EMC_A(6)           /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A6_LABEL "U28[H3]/P1_7-EMC_A6" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A6_NAME "EMC_A6"               /*!<@brief Identifier name */
                                                          /* @} */

/*! @name EMC_A(7) (coord P8), U28[H2]/P1_8-EMC_A7
  @{ */
#define BOARD_INITPINS_EMC_A7_PERIPHERAL EMC              /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A7_SIGNAL EMC_A                /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A7_CHANNEL 7                   /*!<@brief EMC EMC_A channel: 7 */
#define BOARD_INITPINS_EMC_A7_PIN_NAME EMC_A(7)           /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A7_LABEL "U28[H2]/P1_8-EMC_A7" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A7_NAME "EMC_A7"               /*!<@brief Identifier name */
                                                          /* @} */

/*! @name EMC_CASN (coord K6), U28[F7]/P1_9-EMC_CASn
  @{ */
#define BOARD_INITPINS_EMC_CASn_PERIPHERAL EMC                /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_CASn_SIGNAL EMC_CAS                /*!<@brief EMC signal: EMC_CAS */
#define BOARD_INITPINS_EMC_CASn_PIN_NAME EMC_CASN             /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_CASn_LABEL "U28[F7]/P1_9-EMC_CASn" /*!<@brief Label */
#define BOARD_INITPINS_EMC_CASn_NAME "EMC_CASn"               /*!<@brief Identifier name */
                                                              /* @} */

/*! @name EMC_D(8) (coord L1), U28[E1]/RP4[4]/P1_19-EMC_D8
  @{ */
#define BOARD_INITPINS_EMC_D8_PERIPHERAL EMC                      /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D8_SIGNAL EMC_D                        /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D8_CHANNEL 8                           /*!<@brief EMC EMC_D channel: 8 */
#define BOARD_INITPINS_EMC_D8_PIN_NAME EMC_D(8)                   /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D8_LABEL "U28[E1]/RP4[4]/P1_19-EMC_D8" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D8_NAME "EMC_D8"                       /*!<@brief Identifier name */
                                                                  /* @} */

/*! @name EMC_D(9) (coord M1), U28[D2]/RP4[3]/P1_20-EMC_D9
  @{ */
#define BOARD_INITPINS_EMC_D9_PERIPHERAL EMC                      /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D9_SIGNAL EMC_D                        /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D9_CHANNEL 9                           /*!<@brief EMC EMC_D channel: 9 */
#define BOARD_INITPINS_EMC_D9_PIN_NAME EMC_D(9)                   /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D9_LABEL "U28[D2]/RP4[3]/P1_20-EMC_D9" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D9_NAME "EMC_D9"                       /*!<@brief Identifier name */
                                                                  /* @} */

/*! @name EMC_D(10) (coord N8), U28[D1]/RP4[2]/P1_21-EMC_D10
  @{ */
#define BOARD_INITPINS_EMC_D10_PERIPHERAL EMC                       /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D10_SIGNAL EMC_D                         /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D10_CHANNEL 10                           /*!<@brief EMC EMC_D channel: 10 */
#define BOARD_INITPINS_EMC_D10_PIN_NAME EMC_D(10)                   /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D10_LABEL "U28[D1]/RP4[2]/P1_21-EMC_D10" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D10_NAME "EMC_D10"                       /*!<@brief Identifier name */
                                                                    /* @} */

/*! @name EMC_RASN (coord N9), U28[F8]/P1_10-EMC_RASn
  @{ */
#define BOARD_INITPINS_EMC_RASn_PERIPHERAL EMC                 /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_RASn_SIGNAL EMC_RAS                 /*!<@brief EMC signal: EMC_RAS */
#define BOARD_INITPINS_EMC_RASn_PIN_NAME EMC_RASN              /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_RASn_LABEL "U28[F8]/P1_10-EMC_RASn" /*!<@brief Label */
#define BOARD_INITPINS_EMC_RASn_NAME "EMC_RASn"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name EMC_CLK(0) (coord B4), U28[F2]/P1_11-EMC_CLK0
  @{ */
#define BOARD_INITPINS_EMC_CLK0_PERIPHERAL EMC                 /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_CLK0_SIGNAL EMC_CLK                 /*!<@brief EMC signal: EMC_CLK */
#define BOARD_INITPINS_EMC_CLK0_CHANNEL 0                      /*!<@brief EMC EMC_CLK channel: 0 */
#define BOARD_INITPINS_EMC_CLK0_PIN_NAME EMC_CLK(0)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_CLK0_LABEL "U28[F2]/P1_11-EMC_CLK0" /*!<@brief Label */
#define BOARD_INITPINS_EMC_CLK0_NAME "EMC_CLK0"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name EMC_DYCSN(0) (coord K9), U28[G9]/P1_12-EMC_DYCSn0
  @{ */
#define BOARD_INITPINS_EMC_DYCSn0_PERIPHERAL EMC                   /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_DYCSn0_SIGNAL EMC_DYCS                  /*!<@brief EMC signal: EMC_DYCS */
#define BOARD_INITPINS_EMC_DYCSn0_CHANNEL 0                        /*!<@brief EMC EMC_DYCS channel: 0 */
#define BOARD_INITPINS_EMC_DYCSn0_PIN_NAME EMC_DYCSN(0)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_DYCSn0_LABEL "U28[G9]/P1_12-EMC_DYCSn0" /*!<@brief Label */
#define BOARD_INITPINS_EMC_DYCSn0_NAME "EMC_DYCSn0"                /*!<@brief Identifier name */
                                                                   /* @} */

/*! @name EMC_DQM(0) (coord G10), U28[E8]/P1_13-EMC_DQM0
  @{ */
#define BOARD_INITPINS_EMC_DQM0_PERIPHERAL EMC                 /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_DQM0_SIGNAL EMC_DQM                 /*!<@brief EMC signal: EMC_DQM */
#define BOARD_INITPINS_EMC_DQM0_CHANNEL 0                      /*!<@brief EMC EMC_DQM channel: 0 */
#define BOARD_INITPINS_EMC_DQM0_PIN_NAME EMC_DQM(0)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_DQM0_LABEL "U28[E8]/P1_13-EMC_DQM0" /*!<@brief Label */
#define BOARD_INITPINS_EMC_DQM0_NAME "EMC_DQM0"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name EMC_DQM(1) (coord C12), U28[F1]/P1_14-EMC_DQM1
  @{ */
#define BOARD_INITPINS_EMC_DQM1_PERIPHERAL EMC                 /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_DQM1_SIGNAL EMC_DQM                 /*!<@brief EMC signal: EMC_DQM */
#define BOARD_INITPINS_EMC_DQM1_CHANNEL 1                      /*!<@brief EMC EMC_DQM channel: 1 */
#define BOARD_INITPINS_EMC_DQM1_PIN_NAME EMC_DQM(1)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_DQM1_LABEL "U28[F1]/P1_14-EMC_DQM1" /*!<@brief Label */
#define BOARD_INITPINS_EMC_DQM1_NAME "EMC_DQM1"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name EMC_CKE(0) (coord A11), U28[F3]/P1_15-EMC_CKE0
  @{ */
#define BOARD_INITPINS_EMC_CKE0_PERIPHERAL EMC                 /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_CKE0_SIGNAL EMC_CKE                 /*!<@brief EMC signal: EMC_CKE */
#define BOARD_INITPINS_EMC_CKE0_CHANNEL 0                      /*!<@brief EMC EMC_CKE channel: 0 */
#define BOARD_INITPINS_EMC_CKE0_PIN_NAME EMC_CKE(0)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_CKE0_LABEL "U28[F3]/P1_15-EMC_CKE0" /*!<@brief Label */
#define BOARD_INITPINS_EMC_CKE0_NAME "EMC_CKE0"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name EMC_A(10) (coord B7), U28[H9]/P1_16-EMC_A10
  @{ */
#define BOARD_INITPINS_EMC_A10_PERIPHERAL EMC                /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A10_SIGNAL EMC_A                  /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A10_CHANNEL 10                    /*!<@brief EMC EMC_A channel: 10 */
#define BOARD_INITPINS_EMC_A10_PIN_NAME EMC_A(10)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A10_LABEL "U28[H9]/P1_16-EMC_A10" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A10_NAME "EMC_A10"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name EMC_A(11) (coord M10), U28[G2]/P1_23-EMC_A11
  @{ */
#define BOARD_INITPINS_EMC_A11_PERIPHERAL EMC                /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A11_SIGNAL EMC_A                  /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A11_CHANNEL 11                    /*!<@brief EMC EMC_A channel: 11 */
#define BOARD_INITPINS_EMC_A11_PIN_NAME EMC_A(11)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A11_LABEL "U28[G2]/P1_23-EMC_A11" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A11_NAME "EMC_A11"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name EMC_A(12) (coord N14), U28[G1]/P1_24-EMC_A12
  @{ */
#define BOARD_INITPINS_EMC_A12_PERIPHERAL EMC                /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A12_SIGNAL EMC_A                  /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A12_CHANNEL 12                    /*!<@brief EMC EMC_A channel: 12 */
#define BOARD_INITPINS_EMC_A12_PIN_NAME EMC_A(12)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A12_LABEL "U28[G1]/P1_24-EMC_A12" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A12_NAME "EMC_A12"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name EMC_A(13) (coord M12), U28[G7]/P1_25-EMC_A13
  @{ */
#define BOARD_INITPINS_EMC_A13_PERIPHERAL EMC                /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A13_SIGNAL EMC_A                  /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A13_CHANNEL 13                    /*!<@brief EMC EMC_A channel: 13 */
#define BOARD_INITPINS_EMC_A13_PIN_NAME EMC_A(13)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A13_LABEL "U28[G7]/P1_25-EMC_A13" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A13_NAME "EMC_A13"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name EMC_D(12) (coord E12), U28[C1]/RP2[4]/P1_28-EMC_D12
  @{ */
#define BOARD_INITPINS_EMC_D12_PERIPHERAL EMC                       /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D12_SIGNAL EMC_D                         /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D12_CHANNEL 12                           /*!<@brief EMC EMC_D channel: 12 */
#define BOARD_INITPINS_EMC_D12_PIN_NAME EMC_D(12)                   /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D12_LABEL "U28[C1]/RP2[4]/P1_28-EMC_D12" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D12_NAME "EMC_D12"                       /*!<@brief Identifier name */
                                                                    /* @} */

/*! @name EMC_D(13) (coord C11), U28[B2]/RP2[3]/P1_29-EMC_D13
  @{ */
#define BOARD_INITPINS_EMC_D13_PERIPHERAL EMC                       /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D13_SIGNAL EMC_D                         /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D13_CHANNEL 13                           /*!<@brief EMC EMC_D channel: 13 */
#define BOARD_INITPINS_EMC_D13_PIN_NAME EMC_D(13)                   /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D13_LABEL "U28[B2]/RP2[3]/P1_29-EMC_D13" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D13_NAME "EMC_D13"                       /*!<@brief Identifier name */
                                                                    /* @} */

/*! @name EMC_D(14) (coord A8), U28[B1]/RP2[2]/P1_30-EMC_D14
  @{ */
#define BOARD_INITPINS_EMC_D14_PERIPHERAL EMC                       /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D14_SIGNAL EMC_D                         /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D14_CHANNEL 14                           /*!<@brief EMC EMC_D channel: 14 */
#define BOARD_INITPINS_EMC_D14_PIN_NAME EMC_D(14)                   /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D14_LABEL "U28[B1]/RP2[2]/P1_30-EMC_D14" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D14_NAME "EMC_D14"                       /*!<@brief Identifier name */
                                                                    /* @} */

/*! @name EMC_D(15) (coord C5), U28[A2]/RP2[1]/P1_31-EMC_D15
  @{ */
#define BOARD_INITPINS_EMC_D15_PERIPHERAL EMC                       /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_D15_SIGNAL EMC_D                         /*!<@brief EMC signal: EMC_D */
#define BOARD_INITPINS_EMC_D15_CHANNEL 15                           /*!<@brief EMC EMC_D channel: 15 */
#define BOARD_INITPINS_EMC_D15_PIN_NAME EMC_D(15)                   /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_D15_LABEL "U28[A2]/RP2[1]/P1_31-EMC_D15" /*!<@brief Label */
#define BOARD_INITPINS_EMC_D15_NAME "EMC_D15"                       /*!<@brief Identifier name */
                                                                    /* @} */

/*! @name EMC_A(8) (coord J10), U28[H1]/P1_26-EMC_A8
  @{ */
#define BOARD_INITPINS_EMC_A8_PERIPHERAL EMC               /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A8_SIGNAL EMC_A                 /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A8_CHANNEL 8                    /*!<@brief EMC EMC_A channel: 8 */
#define BOARD_INITPINS_EMC_A8_PIN_NAME EMC_A(8)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A8_LABEL "U28[H1]/P1_26-EMC_A8" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A8_NAME "EMC_A8"                /*!<@brief Identifier name */
                                                           /* @} */

/*! @name EMC_A(9) (coord F10), U28[G3]/P1_27-EMC_A9
  @{ */
#define BOARD_INITPINS_EMC_A9_PERIPHERAL EMC               /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A9_SIGNAL EMC_A                 /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A9_CHANNEL 9                    /*!<@brief EMC EMC_A channel: 9 */
#define BOARD_INITPINS_EMC_A9_PIN_NAME EMC_A(9)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A9_LABEL "U28[G3]/P1_27-EMC_A9" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A9_NAME "EMC_A9"                /*!<@brief Identifier name */
                                                           /* @} */

/*! @name EMC_A(14) (coord P9), U28[G8]/P3_25-EMC_A14
  @{ */
#define BOARD_INITPINS_EMC_A14_PERIPHERAL EMC                /*!<@brief Device name: EMC */
#define BOARD_INITPINS_EMC_A14_SIGNAL EMC_A                  /*!<@brief EMC signal: EMC_A */
#define BOARD_INITPINS_EMC_A14_CHANNEL 14                    /*!<@brief EMC EMC_A channel: 14 */
#define BOARD_INITPINS_EMC_A14_PIN_NAME EMC_A(14)            /*!<@brief Pin name */
#define BOARD_INITPINS_EMC_A14_LABEL "U28[G8]/P3_25-EMC_A14" /*!<@brief Label */
#define BOARD_INITPINS_EMC_A14_NAME "EMC_A14"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name LCD_PWR (coord K3), J16[31]/P2_11-LCD_PWR
  @{ */
#define BOARD_INITPINS_LCD_PWR_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_PWR_SIGNAL LCD_PWR                /*!<@brief LCD signal: LCD_PWR */
#define BOARD_INITPINS_LCD_PWR_PIN_NAME LCD_PWR              /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_PWR_LABEL "J16[31]/P2_11-LCD_PWR" /*!<@brief Label */
#define BOARD_INITPINS_LCD_PWR_NAME "LCD_PWR"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name LCD_DCLK (coord P7), J16[30]/P2_13-LCD_DCLK
  @{ */
#define BOARD_INITPINS_LCD_DCLK_PERIPHERAL LCD                 /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_DCLK_SIGNAL LCD_DCLK                /*!<@brief LCD signal: LCD_DCLK */
#define BOARD_INITPINS_LCD_DCLK_PIN_NAME LCD_DCLK              /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_DCLK_LABEL "J16[30]/P2_13-LCD_DCLK" /*!<@brief Label */
#define BOARD_INITPINS_LCD_DCLK_NAME "LCD_DCLK"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name LCD_FP (coord L7), J16[33]/P2_14-LCD_FP
  @{ */
#define BOARD_INITPINS_LCD_FP_PERIPHERAL LCD               /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_FP_SIGNAL LCD_FP                /*!<@brief LCD signal: LCD_FP */
#define BOARD_INITPINS_LCD_FP_PIN_NAME LCD_FP              /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_FP_LABEL "J16[33]/P2_14-LCD_FP" /*!<@brief Label */
#define BOARD_INITPINS_LCD_FP_NAME "LCD_FP"                /*!<@brief Identifier name */
                                                           /* @} */

/*! @name LCD_AC (coord M8), J16[34]/P2_15-LCD_AC_ENAB_M
  @{ */
/*!
 * @brief Device name: LCD */
#define BOARD_INITPINS_LCD_AC_ENAB_M_PERIPHERAL LCD
/*!
 * @brief LCD signal: LCD_AC */
#define BOARD_INITPINS_LCD_AC_ENAB_M_SIGNAL LCD_AC
/*!
 * @brief Pin name */
#define BOARD_INITPINS_LCD_AC_ENAB_M_PIN_NAME LCD_AC
/*!
 * @brief Label */
#define BOARD_INITPINS_LCD_AC_ENAB_M_LABEL "J16[34]/P2_15-LCD_AC_ENAB_M"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_LCD_AC_ENAB_M_NAME "LCD_AC_ENAB_M"
/* @} */

/*! @name LCD_LP (coord L8), J16[32]/P2_16-LCD_LP
  @{ */
#define BOARD_INITPINS_LCD_LP_PERIPHERAL LCD               /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_LP_SIGNAL LCD_LP                /*!<@brief LCD signal: LCD_LP */
#define BOARD_INITPINS_LCD_LP_PIN_NAME LCD_LP              /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_LP_LABEL "J16[32]/P2_16-LCD_LP" /*!<@brief Label */
#define BOARD_INITPINS_LCD_LP_NAME "LCD_LP"                /*!<@brief Identifier name */
                                                           /* @} */

/*! @name LCD_VD(3) (coord L10), J16[8]/P2_21-LCD_VD3
  @{ */
#define BOARD_INITPINS_LCD_VD3_PERIPHERAL LCD               /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD3_SIGNAL LCD_VD                /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD3_CHANNEL 3                    /*!<@brief LCD LCD_VD channel: 3 */
#define BOARD_INITPINS_LCD_VD3_PIN_NAME LCD_VD(3)           /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD3_LABEL "J16[8]/P2_21-LCD_VD3" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD3_NAME "LCD_VD3"               /*!<@brief Identifier name */
                                                            /* @} */

/*! @name LCD_VD(4) (coord K10), J16[9]/P2_22-LCD_VD4
  @{ */
#define BOARD_INITPINS_LCD_VD4_PERIPHERAL LCD               /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD4_SIGNAL LCD_VD                /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD4_CHANNEL 4                    /*!<@brief LCD LCD_VD channel: 4 */
#define BOARD_INITPINS_LCD_VD4_PIN_NAME LCD_VD(4)           /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD4_LABEL "J16[9]/P2_22-LCD_VD4" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD4_NAME "LCD_VD4"               /*!<@brief Identifier name */
                                                            /* @} */

/*! @name LCD_VD(5) (coord M14), J16[10]/P2_23-LCD_VD5
  @{ */
#define BOARD_INITPINS_LCD_VD5_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD5_SIGNAL LCD_VD                 /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD5_CHANNEL 5                     /*!<@brief LCD LCD_VD channel: 5 */
#define BOARD_INITPINS_LCD_VD5_PIN_NAME LCD_VD(5)            /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD5_LABEL "J16[10]/P2_23-LCD_VD5" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD5_NAME "LCD_VD5"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name LCD_VD(6) (coord K14), J16[11]/P2_24-LCD_VD6
  @{ */
#define BOARD_INITPINS_LCD_VD6_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD6_SIGNAL LCD_VD                 /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD6_CHANNEL 6                     /*!<@brief LCD LCD_VD channel: 6 */
#define BOARD_INITPINS_LCD_VD6_PIN_NAME LCD_VD(6)            /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD6_LABEL "J16[11]/P2_24-LCD_VD6" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD6_NAME "LCD_VD6"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name LCD_VD(7) (coord J11), J16[12]/P2_25-LCD_VD7
  @{ */
#define BOARD_INITPINS_LCD_VD7_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD7_SIGNAL LCD_VD                 /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD7_CHANNEL 7                     /*!<@brief LCD LCD_VD channel: 7 */
#define BOARD_INITPINS_LCD_VD7_PIN_NAME LCD_VD(7)            /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD7_LABEL "J16[12]/P2_25-LCD_VD7" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD7_NAME "LCD_VD7"                /*!<@brief Identifier name */
                                                             /* @} */

/*! @name LCD_VD(10) (coord G13), J16[15]/P2_28-LCD_VD10
  @{ */
#define BOARD_INITPINS_LCD_VD10_PERIPHERAL LCD                 /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD10_SIGNAL LCD_VD                  /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD10_CHANNEL 10                     /*!<@brief LCD LCD_VD channel: 10 */
#define BOARD_INITPINS_LCD_VD10_PIN_NAME LCD_VD(10)            /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD10_LABEL "J16[15]/P2_28-LCD_VD10" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD10_NAME "LCD_VD10"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name LCD_VD(11) (coord G11), J16[16]/P2_29-LCD_VD11
  @{ */
#define BOARD_INITPINS_LCD_VD11_PERIPHERAL LCD                 /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD11_SIGNAL LCD_VD                  /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD11_CHANNEL 11                     /*!<@brief LCD LCD_VD channel: 11 */
#define BOARD_INITPINS_LCD_VD11_PIN_NAME LCD_VD(11)            /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD11_LABEL "J16[16]/P2_29-LCD_VD11" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD11_NAME "LCD_VD11"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name LCD_VD(12) (coord F12), J16[17]/P2_30-LCD_VD12
  @{ */
#define BOARD_INITPINS_LCD_VD12_PERIPHERAL LCD                 /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD12_SIGNAL LCD_VD                  /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD12_CHANNEL 12                     /*!<@brief LCD LCD_VD channel: 12 */
#define BOARD_INITPINS_LCD_VD12_PIN_NAME LCD_VD(12)            /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD12_LABEL "J16[17]/P2_30-LCD_VD12" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD12_NAME "LCD_VD12"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name LCD_VD(13) (coord D14), J16[18]/P2_31-LCD_VD13
  @{ */
#define BOARD_INITPINS_LCD_VD13_PERIPHERAL LCD                 /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD13_SIGNAL LCD_VD                  /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD13_CHANNEL 13                     /*!<@brief LCD LCD_VD channel: 13 */
#define BOARD_INITPINS_LCD_VD13_PIN_NAME LCD_VD(13)            /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD13_LABEL "J16[18]/P2_31-LCD_VD13" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD13_NAME "LCD_VD13"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name LCD_VD(14) (coord D12), J16[19]/JS36[1]/P3_0-LCD_VD14
  @{ */
#define BOARD_INITPINS_LCD_VD14_PERIPHERAL LCD                        /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD14_SIGNAL LCD_VD                         /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD14_CHANNEL 14                            /*!<@brief LCD LCD_VD channel: 14 */
#define BOARD_INITPINS_LCD_VD14_PIN_NAME LCD_VD(14)                   /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD14_LABEL "J16[19]/JS36[1]/P3_0-LCD_VD14" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD14_NAME "LCD_VD14"                       /*!<@brief Identifier name */
                                                                      /* @} */

/*! @name LCD_VD(15) (coord D11), J16[20]/JS33[1]/P3_1-LCD_VD15
  @{ */
#define BOARD_INITPINS_LCD_VD15_PERIPHERAL LCD                        /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD15_SIGNAL LCD_VD                         /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD15_CHANNEL 15                            /*!<@brief LCD LCD_VD channel: 15 */
#define BOARD_INITPINS_LCD_VD15_PIN_NAME LCD_VD(15)                   /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD15_LABEL "J16[20]/JS33[1]/P3_1-LCD_VD15" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD15_NAME "LCD_VD15"                       /*!<@brief Identifier name */
                                                                      /* @} */

/*! @name LCD_VD(19) (coord B10), J16[24]/P3_5-LCD_VD19
  @{ */
#define BOARD_INITPINS_LCD_VD19_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD19_SIGNAL LCD_VD                 /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD19_CHANNEL 19                    /*!<@brief LCD LCD_VD channel: 19 */
#define BOARD_INITPINS_LCD_VD19_PIN_NAME LCD_VD(19)           /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD19_LABEL "J16[24]/P3_5-LCD_VD19" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD19_NAME "LCD_VD19"               /*!<@brief Identifier name */
                                                              /* @} */

/*! @name LCD_VD(20) (coord C9), J16[25]/P3_6-LCD_VD20
  @{ */
#define BOARD_INITPINS_LCD_VD20_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD20_SIGNAL LCD_VD                 /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD20_CHANNEL 20                    /*!<@brief LCD LCD_VD channel: 20 */
#define BOARD_INITPINS_LCD_VD20_PIN_NAME LCD_VD(20)           /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD20_LABEL "J16[25]/P3_6-LCD_VD20" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD20_NAME "LCD_VD20"               /*!<@brief Identifier name */
                                                              /* @} */

/*! @name LCD_VD(21) (coord B8), J16[26]/P3_7-LCD_VD21
  @{ */
#define BOARD_INITPINS_LCD_VD21_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD21_SIGNAL LCD_VD                 /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD21_CHANNEL 21                    /*!<@brief LCD LCD_VD channel: 21 */
#define BOARD_INITPINS_LCD_VD21_PIN_NAME LCD_VD(21)           /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD21_LABEL "J16[26]/P3_7-LCD_VD21" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD21_NAME "LCD_VD21"               /*!<@brief Identifier name */
                                                              /* @} */

/*! @name LCD_VD(22) (coord A7), J16[27]/P3_8-LCD_VD22
  @{ */
#define BOARD_INITPINS_LCD_VD22_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD22_SIGNAL LCD_VD                 /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD22_CHANNEL 22                    /*!<@brief LCD LCD_VD channel: 22 */
#define BOARD_INITPINS_LCD_VD22_PIN_NAME LCD_VD(22)           /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD22_LABEL "J16[27]/P3_8-LCD_VD22" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD22_NAME "LCD_VD22"               /*!<@brief Identifier name */
                                                              /* @} */

/*! @name LCD_VD(23) (coord C7), J16[28]/P3_9-LCD_VD23
  @{ */
#define BOARD_INITPINS_LCD_VD23_PERIPHERAL LCD                /*!<@brief Device name: LCD */
#define BOARD_INITPINS_LCD_VD23_SIGNAL LCD_VD                 /*!<@brief LCD signal: LCD_VD */
#define BOARD_INITPINS_LCD_VD23_CHANNEL 23                    /*!<@brief LCD LCD_VD channel: 23 */
#define BOARD_INITPINS_LCD_VD23_PIN_NAME LCD_VD(23)           /*!<@brief Pin name */
#define BOARD_INITPINS_LCD_VD23_LABEL "J16[28]/P3_9-LCD_VD23" /*!<@brief Label */
#define BOARD_INITPINS_LCD_VD23_NAME "LCD_VD23"               /*!<@brief Identifier name */
                                                              /* @} */

/*! @name FC2_CTS_SDA_SSEL0 (coord C2), J11[10]/J9[3]/U10[3]/J17[5]/U19[10]/P3_23-FC2_SDAX
  @{ */
/*!
 * @brief Device name: FLEXCOMM2 */
#define BOARD_INITPINS_FC2_SDAX_PERIPHERAL FLEXCOMM2
/*!
 * @brief FLEXCOMM2 signal: CTS_SDA_SSEL0 */
#define BOARD_INITPINS_FC2_SDAX_SIGNAL CTS_SDA_SSEL0
/*!
 * @brief Pin name */
#define BOARD_INITPINS_FC2_SDAX_PIN_NAME FC2_CTS_SDA_SSEL0
/*!
 * @brief Label */
#define BOARD_INITPINS_FC2_SDAX_LABEL "J11[10]/J9[3]/U10[3]/J17[5]/U19[10]/P3_23-FC2_SDAX"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_FC2_SDAX_NAME "FC2_SDAX"
/* @} */

/*! @name FC2_RTS_SCL_SSEL1 (coord E2), J11[9]/J9[1]/U10[2]/J17[4]/U19[2]/P3_24-FC2_SCLX
  @{ */
/*!
 * @brief Device name: FLEXCOMM2 */
#define BOARD_INITPINS_FC2_SCLX_PERIPHERAL FLEXCOMM2
/*!
 * @brief FLEXCOMM2 signal: RTS_SCL_SSEL1 */
#define BOARD_INITPINS_FC2_SCLX_SIGNAL RTS_SCL_SSEL1
/*!
 * @brief Pin name */
#define BOARD_INITPINS_FC2_SCLX_PIN_NAME FC2_RTS_SCL_SSEL1
/*!
 * @brief Label */
#define BOARD_INITPINS_FC2_SCLX_LABEL "J11[9]/J9[1]/U10[2]/J17[4]/U19[2]/P3_24-FC2_SCLX"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_FC2_SCLX_NAME "FC2_SCLX"
/* @} */

/*! @name ENET_TXD0 (coord B14), U12[17]/JP11[1]/P4_8-ENET_TXD0
  @{ */
/*!
 * @brief Device name: ENET */
#define BOARD_INITPINS_ENET_TXD0_PERIPHERAL ENET
/*!
 * @brief ENET signal: ENET_TXD */
#define BOARD_INITPINS_ENET_TXD0_SIGNAL ENET_TXD
/*!
 * @brief ENET ENET_TXD channel: 0 */
#define BOARD_INITPINS_ENET_TXD0_CHANNEL 0
/*!
 * @brief Pin name */
#define BOARD_INITPINS_ENET_TXD0_PIN_NAME ENET_TXD0
/*!
 * @brief Label */
#define BOARD_INITPINS_ENET_TXD0_LABEL "U12[17]/JP11[1]/P4_8-ENET_TXD0"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_ENET_TXD0_NAME "ENET_TXD0"
/* @} */

/*! @name ENET_RX_DV (coord B9), U12[11]/P4_10-ENET_CRS_DV
  @{ */
#define BOARD_INITPINS_ENET_CRS_DV_PERIPHERAL ENET                   /*!<@brief Device name: ENET */
#define BOARD_INITPINS_ENET_CRS_DV_SIGNAL ENET_RX_DV                 /*!<@brief ENET signal: ENET_RX_DV */
#define BOARD_INITPINS_ENET_CRS_DV_PIN_NAME ENET_RX_DV               /*!<@brief Pin name */
#define BOARD_INITPINS_ENET_CRS_DV_LABEL "U12[11]/P4_10-ENET_CRS_DV" /*!<@brief Label */
#define BOARD_INITPINS_ENET_CRS_DV_NAME "ENET_CRS_DV"                /*!<@brief Identifier name */
                                                                     /* @} */

/*! @name ENET_RXD1 (coord A6), U12[7]/P4_12-ENET_RXD1
  @{ */
#define BOARD_INITPINS_ENET_RXD1_PERIPHERAL ENET                /*!<@brief Device name: ENET */
#define BOARD_INITPINS_ENET_RXD1_SIGNAL ENET_RXD                /*!<@brief ENET signal: ENET_RXD */
#define BOARD_INITPINS_ENET_RXD1_CHANNEL 1                      /*!<@brief ENET ENET_RXD channel: 1 */
#define BOARD_INITPINS_ENET_RXD1_PIN_NAME ENET_RXD1             /*!<@brief Pin name */
#define BOARD_INITPINS_ENET_RXD1_LABEL "U12[7]/P4_12-ENET_RXD1" /*!<@brief Label */
#define BOARD_INITPINS_ENET_RXD1_NAME "ENET_RXD1"               /*!<@brief Identifier name */
                                                                /* @} */

/*! @name ENET_TX_EN (coord B6), U12[16]/P4_13-ENET_TX_EN
  @{ */
#define BOARD_INITPINS_ENET_TX_EN_PERIPHERAL ENET                  /*!<@brief Device name: ENET */
#define BOARD_INITPINS_ENET_TX_EN_SIGNAL ENET_TX_EN                /*!<@brief ENET signal: ENET_TX_EN */
#define BOARD_INITPINS_ENET_TX_EN_PIN_NAME ENET_TX_EN              /*!<@brief Pin name */
#define BOARD_INITPINS_ENET_TX_EN_LABEL "U12[16]/P4_13-ENET_TX_EN" /*!<@brief Label */
#define BOARD_INITPINS_ENET_TX_EN_NAME "ENET_TX_EN"                /*!<@brief Identifier name */
                                                                   /* @} */

/*! @name ENET_RX_CLK (coord B5), JS18[2]/P4_14-ENET_RX_CLK
  @{ */
#define BOARD_INITPINS_ENET_RX_CLK_PERIPHERAL ENET                   /*!<@brief Device name: ENET */
#define BOARD_INITPINS_ENET_RX_CLK_SIGNAL ENET_RX_CLK                /*!<@brief ENET signal: ENET_RX_CLK */
#define BOARD_INITPINS_ENET_RX_CLK_PIN_NAME ENET_RX_CLK              /*!<@brief Pin name */
#define BOARD_INITPINS_ENET_RX_CLK_LABEL "JS18[2]/P4_14-ENET_RX_CLK" /*!<@brief Label */
#define BOARD_INITPINS_ENET_RX_CLK_NAME "ENET_RX_CLK"                /*!<@brief Identifier name */
                                                                     /* @} */

/*! @name ENET_MDC (coord A4), U12[13]/P4_15-ENET_MDC
  @{ */
#define BOARD_INITPINS_ENET_MDC_PERIPHERAL ENET                /*!<@brief Device name: ENET */
#define BOARD_INITPINS_ENET_MDC_SIGNAL ENET_MDC                /*!<@brief ENET signal: ENET_MDC */
#define BOARD_INITPINS_ENET_MDC_PIN_NAME ENET_MDC              /*!<@brief Pin name */
#define BOARD_INITPINS_ENET_MDC_LABEL "U12[13]/P4_15-ENET_MDC" /*!<@brief Label */
#define BOARD_INITPINS_ENET_MDC_NAME "ENET_MDC"                /*!<@brief Identifier name */
                                                               /* @} */

/*! @name ENET_MDIO (coord C4), U12[12]/P4_16-ENET_MDIO
  @{ */
#define BOARD_INITPINS_ENET_MDIO_PERIPHERAL ENET                 /*!<@brief Device name: ENET */
#define BOARD_INITPINS_ENET_MDIO_SIGNAL ENET_MDIO                /*!<@brief ENET signal: ENET_MDIO */
#define BOARD_INITPINS_ENET_MDIO_PIN_NAME ENET_MDIO              /*!<@brief Pin name */
#define BOARD_INITPINS_ENET_MDIO_LABEL "U12[12]/P4_16-ENET_MDIO" /*!<@brief Label */
#define BOARD_INITPINS_ENET_MDIO_NAME "ENET_MDIO"                /*!<@brief Identifier name */
                                                                 /* @} */

/*! @name ENET_TXD1 (coord E14), U12[18]/P0_17-ENET_TXD1
  @{ */
#define BOARD_INITPINS_ENET_TXD1_PERIPHERAL ENET                 /*!<@brief Device name: ENET */
#define BOARD_INITPINS_ENET_TXD1_SIGNAL ENET_TXD                 /*!<@brief ENET signal: ENET_TXD */
#define BOARD_INITPINS_ENET_TXD1_CHANNEL 1                       /*!<@brief ENET ENET_TXD channel: 1 */
#define BOARD_INITPINS_ENET_TXD1_PIN_NAME ENET_TXD1              /*!<@brief Pin name */
#define BOARD_INITPINS_ENET_TXD1_LABEL "U12[18]/P0_17-ENET_TXD1" /*!<@brief Label */
#define BOARD_INITPINS_ENET_TXD1_NAME "ENET_TXD1"                /*!<@brief Identifier name */
                                                                 /* @} */

/*! @name PIO2_26 (coord H11), U12[15]/P2_26-ENET_PHY_RSTn
  @{ */
/*!
 * @brief Device name: GPIO */
#define BOARD_INITPINS_ENET_PHY_RSTn_PERIPHERAL GPIO
/*!
 * @brief GPIO signal: PIO2 */
#define BOARD_INITPINS_ENET_PHY_RSTn_SIGNAL PIO2
/*!
 * @brief GPIO device name: GPIO */
#define BOARD_INITPINS_ENET_PHY_RSTn_GPIO GPIO
/*!
 * @brief PIO2 pin index: 26 */
#define BOARD_INITPINS_ENET_PHY_RSTn_GPIO_PIN 26U
/*!
 * @brief PORT device name: 2U */
#define BOARD_INITPINS_ENET_PHY_RSTn_PORT 2U
/*!
 * @brief 2U pin index: 26 */
#define BOARD_INITPINS_ENET_PHY_RSTn_PIN 26U
/*!
 * @brief GPIO PIO2 channel: 26 */
#define BOARD_INITPINS_ENET_PHY_RSTn_CHANNEL 26
/*!
 * @brief Pin name */
#define BOARD_INITPINS_ENET_PHY_RSTn_PIN_NAME PIO2_26
/*!
 * @brief Label */
#define BOARD_INITPINS_ENET_PHY_RSTn_LABEL "U12[15]/P2_26-ENET_PHY_RSTn"
/*!
 * @brief Identifier name */
#define BOARD_INITPINS_ENET_PHY_RSTn_NAME "ENET_PHY_RSTn"
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
