//#include "wiced_resource.h"
#include <certs/certs.h>
/* aws */
#ifdef AWS
const char clientCert[] = "-----BEGIN CERTIFICATE-----\n" \
"MIIDWTCCAkGgAwIBAgIUafLBL4SZYEk1J6znQma8DrXmoecwDQYJKoZIhvcNAQEL\n" \
"BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g\n" \
"SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTE4MDYyOTA5MDQ1\n" \
"MVoXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0\n" \
"ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKUc+h/zZR7jSTRk5qvT\n" \
"DCSWa3S27ABp9aQEwhn7zQ67gCq5Yx0navTCHaKkqq1WQ8Ams1fd0uxSoYs3wkr+\n" \
"Zh8lDGgLXQzK0l29G9XE5AMh8wy5DAtDkws93kTUukpf3qTgb0odQfqyblDLni3t\n" \
"L8hQS5r39JdijIKGMzdaXIZc7eQSA52OBhPqa18LacfqGLgyEWwnu5KGqGdXoPYI\n" \
"aqfMyh08EM5i+EYkZI3N+r7TMc6PK9zwFAGMstwSUGVH8nWcO426I29fSR9bsoaV\n" \
"KWb9oZGCZAYZ25FMxmiUGHLDQHe0IkJk72X9mPnHu4fTX71GGuJ8rHH8R9YWGPic\n" \
"EqkCAwEAAaNgMF4wHwYDVR0jBBgwFoAUO/yNGrgt8jgXs1ch+2q6EUu8CNswHQYD\n" \
"VR0OBBYEFMHtS6fp55J79r5o7OPdDr+dWsOEMAwGA1UdEwEB/wQCMAAwDgYDVR0P\n" \
"AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQCUXtjYqt7/LROAgRlDG+wOmXF1\n" \
"eW75bC8IuaBvUaFC0oF+9BJKWr6HPUS1JdslVoNfnxAFSzQbZAZiVThROoRh9F5Z\n" \
"c2eBLWvIAgeHgF0tn39NqF9aozFzRFrpiKn/YERgccG6qBBWb7AcrjFCgV0HBKf1\n" \
"dVq9EiXq9QeyzPTTfhGkXDbK5MVADHZSenkIc/OUWa/GcFWvgpM+yk9xKkecrOdJ\n" \
"MB1JeTgiT66KZD9uV4svCx/PY5/xUYjczAfS1PfhGCS+bsIauiLMuajke9CdfzUs\n" \
"GpzNw02GFaVTcaQzgIfXICbkQFfDYHsNpCKWaaLYokB+rCEAhMMwPWihzl7k\n" \
"-----END CERTIFICATE-----\n";
#else
/* raspberry pi */
const char clientCert[] = "-----BEGIN CERTIFICATE-----\n" \
"MIIEUTCCAzmgAwIBAgIJAK13AaG3IKRSMA0GCSqGSIb3DQEBDQUAMGoxFzAVBgNV\n" \
"BAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQwEgYD\n" \
"VQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUu\n" \
"bmV0MB4XDTE3MTIyOTEzMzQyNFoXDTMyMTIyNTEzMzQyNFowHjEcMBoGA1UEAwwT\n" \
"Y2hhdS1ubUBob3RtYWlsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC\n" \
"ggEBALdfwd5as+Pab6Ez46NjdnWVvVnJQZezzLsUemjCzO/ZxINpIgXXZTY0ChFX\n" \
"2sqJogFQgUAzMW+JF1l4VSwZa05QQ+ERNVrm2T1gbEWPT4L499D9lzViAYrjtCsS\n" \
"q5SNcjpzsG0fOcTcylmMwL/mCrBS92HzfBf+fy3It8A23Q35QJewX48CzmqwFJpB\n" \
"To29M+kdgWdEWKjmp5WrOS2Dvox0BdNyVr8D804qSNZg1K3+04jSd6jZ9uFy1Ec7\n" \
"RsHwXkJzzOFXF5ndw+syD0AUMZQ7Qtx5XvS6y0xjr1/Iqe3s43k9G9dduobJ73SR\n" \
"ZlGpVvsCXPS5aYHYIzwifk6JHxECAwEAAaOCAUQwggFAMAwGA1UdEwEB/wQCMAAw\n" \
"CQYDVR0RBAIwADARBglghkgBhvhCAQEEBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH\n" \
"AwIGCCsGAQUFBwMEMAsGA1UdDwQEAwIDqDAoBglghkgBhvhCAQ0EGxYZQ2xpZW50\n" \
"IEJyb2tlciBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUz8Md3iOzxohYEaDNpWYpLrXJ\n" \
"lawwgZwGA1UdIwSBlDCBkYAUMufALRB0NJm261Nc3HZxBiMWJDuhbqRsMGoxFzAV\n" \
"BgNVBAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQw\n" \
"EgYDVQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w\n" \
"bGUubmV0ggkAqmLdPCn7cpkwDQYJKoZIhvcNAQENBQADggEBAJfXR7ev8nbFZiYe\n" \
"Ehs5VdDVuiIwVmPMfAR0Q2znCtaq3rZ+f/kAwgAvN++BWRvze2iL5j1ohP72kR9c\n" \
"iz1F1QJrGPHExQZUDbPBuhQCwRt/xIa6MnfzDvYt5vpnCxMpG3UoyNgARoiNbiD7\n" \
"ulgqkIFFpNrR2U1G9Oh46wiC4wFt7PIduueRJOkEBvVQi8TBHzDhSQ/Cq2bOUQWe\n" \
"pA17MteHUAEJHSb4BRq3ApIdkxfIuGj1HCexsEBmbniJ46SByeofQpEZBV76rpb8\n" \
"u0QToVy/ZRCGOdpVqMxjrKKM19xRz3+NHiQKy05pSipfpTmYFwCqyMMAhFzs6tMy\n" \
"7GOwH1I=\n" \
"-----END CERTIFICATE-----\n";
#endif
const size_t clientCertSize = sizeof(clientCert);
