//#include "wiced_resource.h"
#include <certs/certs.h>

const char clientCert[] = "-----BEGIN CERTIFICATE-----\n" \
"MIIEUTCCAzmgAwIBAgIJAPQu+iGdlBPqMA0GCSqGSIb3DQEBDQUAMGoxFzAVBgNV\n" \
"BAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQwEgYD\n" \
"VQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUu\n" \
"bmV0MB4XDTE3MTEyOTAyMjYzOFoXDTMyMTEyNTAyMjYzOFowHjEcMBoGA1UEAxQT\n" \
"Y2hhdS1ubUBob3RtYWlsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC\n" \
"ggEBAK0GXXKnon5EiTIMZXYMND/jueOIQ8656ZXcSt9OkY/caEWrNFJpMo1IJHZH\n" \
"As56xU/XrI43r78Y5Fx2oNfpO25VtuXyrdmRMxwuQgh0dBTFsdox5pgedHx/Uk7b\n" \
"AVK5IljsEGXb73LOxqb9fD3b7uQhCF6etxLzL3A8i1qWInQDOTWQKq+v+/wQO5Jg\n" \
"q+SyAVzNvsT5qHJoEEt4W7GQBgspV2iqWLle7Zw7l1OdJ8pqZY+Ztae5wisoEMtU\n" \
"fraD4MJ5awDlZ0UDI2dIj5Nr8bsjydWwDRCAYispLeuBAMDztAYCCgsVzHWIyqom\n" \
"3nazSyefxQQz0JZcIQAe9GL/nz8CAwEAAaOCAUQwggFAMAwGA1UdEwEB/wQCMAAw\n" \
"CQYDVR0RBAIwADARBglghkgBhvhCAQEEBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH\n" \
"AwIGCCsGAQUFBwMEMAsGA1UdDwQEAwIDqDAoBglghkgBhvhCAQ0EGxYZQ2xpZW50\n" \
"IEJyb2tlciBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUKh4EVXOkchVBi6dMyQPgPLZ7\n" \
"YAEwgZwGA1UdIwSBlDCBkYAUyvtZX8XiyMjkbGow6nYG8fTwgVuhbqRsMGoxFzAV\n" \
"BgNVBAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQw\n" \
"EgYDVQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w\n" \
"bGUubmV0ggkAvtdBWXC2ix8wDQYJKoZIhvcNAQENBQADggEBAMTKrz79U0auX6x8\n" \
"XfrwtwtsUdlEbIVgx8CkYSxHKFh0p7wbCRZkch+Ydkk+olQZt0pU1kA2Q5DEWaCU\n" \
"uHhGmdXRMqYqbCG7mbFuyRJRpVASpnNnA0dBDAdF/IgyaHUfM3Y9BqB/ti7NSTvV\n" \
"AYGCkzf/QQODygUyH8OSQTuHi152r2O7Tnk9d0JQl3AtivHJu2x0YNVNPFi7eSfG\n" \
"HdWY4FnKwKzHPd1naZQGCBcFPOeJsCD50UUvTnZutJdSurSUWWH94f+6brhADheA\n" \
"wUBMXzpn0qTQm1i06jWKG5SxcqCPPdBfXLGS+YGQLmqShbMW7qP0xGB0Z30dZayV\n" \
"5l69ewY=\n" \
"-----END CERTIFICATE-----\n";

const size_t clientCertSize = sizeof(clientCert);
