//#include "wiced_resource.h"
#include <certs/certs.h>
/*
const char clientCert[] = "-----BEGIN CERTIFICATE-----\n" \
"MIIEUTCCAzmgAwIBAgIJAPQu+iGdlBPqMA0GCSqGSIb3DQEBDQUAMGoxFzAVBgNV\n" \
"BAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQwEgYD\n" \
"VQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUu\n" \
"bmV0MB4XDTE3MTEyOTAyMjYzOFoXDTMyMTEyNTAyMjYzOFowHjEcMBoGA1UEAxQT\n" \
"Y2hhdS1ubUBob3RtYWlsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC\n" \
"ggEBAK0GXXKnon5EiTIMZXYMND/jueOIQ8656ZXcSt9OkY/caEWrNFJpMo1IJHZH\n" \
"As56xU/XrI43r78Y5Fx2oNfpO25VtuXyrdmRMxwuQgh0dBTFsdox5pgedHx/Uk7b\n" \
"AVK5IljsEGXb73LOxqb9fD3b7uQhCF6etxLzL3A8i1qWInQDOTWQKq+v+/wQO5Jg\n" \
"q+SyAVzNvsT5qHJoEEt4W7GQBgspV2iqWLle7Zw7l1OdJ8pqZY+Ztae5wisoEMtU\n" \
"fraD4MJ5awDlZ0UDI2dIj5Nr8bsjydWwDRCAYispLeuBAMDztAYCCgsVzHWIyqom\n" \
"3nazSyefxQQz0JZcIQAe9GL/nz8CAwEAAaOCAUQwggFAMAwGA1UdEwEB/wQCMAAw\n" \
"CQYDVR0RBAIwADARBglghkgBhvhCAQEEBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH\n" \
"AwIGCCsGAQUFBwMEMAsGA1UdDwQEAwIDqDAoBglghkgBhvhCAQ0EGxYZQ2xpZW50\n" \
"IEJyb2tlciBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUKh4EVXOkchVBi6dMyQPgPLZ7\n" \
"YAEwgZwGA1UdIwSBlDCBkYAUyvtZX8XiyMjkbGow6nYG8fTwgVuhbqRsMGoxFzAV\n" \
"BgNVBAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQw\n" \
"EgYDVQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w\n" \
"bGUubmV0ggkAvtdBWXC2ix8wDQYJKoZIhvcNAQENBQADggEBAMTKrz79U0auX6x8\n" \
"XfrwtwtsUdlEbIVgx8CkYSxHKFh0p7wbCRZkch+Ydkk+olQZt0pU1kA2Q5DEWaCU\n" \
"uHhGmdXRMqYqbCG7mbFuyRJRpVASpnNnA0dBDAdF/IgyaHUfM3Y9BqB/ti7NSTvV\n" \
"AYGCkzf/QQODygUyH8OSQTuHi152r2O7Tnk9d0JQl3AtivHJu2x0YNVNPFi7eSfG\n" \
"HdWY4FnKwKzHPd1naZQGCBcFPOeJsCD50UUvTnZutJdSurSUWWH94f+6brhADheA\n" \
"wUBMXzpn0qTQm1i06jWKG5SxcqCPPdBfXLGS+YGQLmqShbMW7qP0xGB0Z30dZayV\n" \
"5l69ewY=\n" \
"-----END CERTIFICATE-----\n";
*/

const char clientCert[] = "-----BEGIN CERTIFICATE-----\n" \
"MIIEUTCCAzmgAwIBAgIJAK13AaG3IKRSMA0GCSqGSIb3DQEBDQUAMGoxFzAVBgNV\n" \
"BAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQwEgYD\n" \
"VQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUu\n" \
"bmV0MB4XDTE3MTIyOTEzMzQyNFoXDTMyMTIyNTEzMzQyNFowHjEcMBoGA1UEAwwT\n" \
"Y2hhdS1ubUBob3RtYWlsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC\n" \
"ggEBALdfwd5as+Pab6Ez46NjdnWVvVnJQZezzLsUemjCzO/ZxINpIgXXZTY0ChFX\n" \
"2sqJogFQgUAzMW+JF1l4VSwZa05QQ+ERNVrm2T1gbEWPT4L499D9lzViAYrjtCsS\n" \
"q5SNcjpzsG0fOcTcylmMwL/mCrBS92HzfBf+fy3It8A23Q35QJewX48CzmqwFJpB\n" \
"To29M+kdgWdEWKjmp5WrOS2Dvox0BdNyVr8D804qSNZg1K3+04jSd6jZ9uFy1Ec7\n" \
"RsHwXkJzzOFXF5ndw+syD0AUMZQ7Qtx5XvS6y0xjr1/Iqe3s43k9G9dduobJ73SR\n" \
"ZlGpVvsCXPS5aYHYIzwifk6JHxECAwEAAaOCAUQwggFAMAwGA1UdEwEB/wQCMAAw\n" \
"CQYDVR0RBAIwADARBglghkgBhvhCAQEEBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH\n" \
"AwIGCCsGAQUFBwMEMAsGA1UdDwQEAwIDqDAoBglghkgBhvhCAQ0EGxYZQ2xpZW50\n" \
"IEJyb2tlciBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUz8Md3iOzxohYEaDNpWYpLrXJ\n" \
"lawwgZwGA1UdIwSBlDCBkYAUMufALRB0NJm261Nc3HZxBiMWJDuhbqRsMGoxFzAV\n" \
"BgNVBAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQw\n" \
"EgYDVQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1w\n" \
"bGUubmV0ggkAqmLdPCn7cpkwDQYJKoZIhvcNAQENBQADggEBAJfXR7ev8nbFZiYe\n" \
"Ehs5VdDVuiIwVmPMfAR0Q2znCtaq3rZ+f/kAwgAvN++BWRvze2iL5j1ohP72kR9c\n" \
"iz1F1QJrGPHExQZUDbPBuhQCwRt/xIa6MnfzDvYt5vpnCxMpG3UoyNgARoiNbiD7\n" \
"ulgqkIFFpNrR2U1G9Oh46wiC4wFt7PIduueRJOkEBvVQi8TBHzDhSQ/Cq2bOUQWe\n" \
"pA17MteHUAEJHSb4BRq3ApIdkxfIuGj1HCexsEBmbniJ46SByeofQpEZBV76rpb8\n" \
"u0QToVy/ZRCGOdpVqMxjrKKM19xRz3+NHiQKy05pSipfpTmYFwCqyMMAhFzs6tMy\n" \
"7GOwH1I=\n" \
"-----END CERTIFICATE-----\n";

const size_t clientCertSize = sizeof(clientCert);
